version: '3.3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80" # Map port 80 to port 80 on the host
      - "443:443" # Map port 443 to port 443 on the host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress
    networks:
      - nginx_wordpress_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - wordpress.env
    networks:
      - nginx_wordpress_network

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    env_file:
      - wordpress.env
      - mysql.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - nginx_wordpress_network

volumes:
  wordpress_data:
  db_data:

networks:
  nginx_wordpress_network:
    driver: bridge
